/*
File generated by js-routes 1.4.9
Based on Rails 6.0.2.2 routes of IntertiaProjects::Application
 */

(function() {
  var DeprecatedGlobbingBehavior, NodeTypes, ParameterMissing, ReservedOptions, SpecialOptionsKey, UriEncoderSegmentRegex, Utils, result, root,
    hasProp = {}.hasOwnProperty,
    slice = [].slice;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  ParameterMissing = function(message, fileName, lineNumber) {
    var instance;
    instance = new Error(message, fileName, lineNumber);
    if (Object.setPrototypeOf) {
      Object.setPrototypeOf(instance, Object.getPrototypeOf(this));
    } else {
      instance.__proto__ = this.__proto__;
    }
    if (Error.captureStackTrace) {
      Error.captureStackTrace(instance, ParameterMissing);
    }
    return instance;
  };

  ParameterMissing.prototype = Object.create(Error.prototype, {
    constructor: {
      value: Error,
      enumerable: false,
      writable: true,
      configurable: true
    }
  });

  if (Object.setPrototypeOf) {
    Object.setPrototypeOf(ParameterMissing, Error);
  } else {
    ParameterMissing.__proto__ = Error;
  }

  NodeTypes = {"GROUP":1,"CAT":2,"SYMBOL":3,"OR":4,"STAR":5,"LITERAL":6,"SLASH":7,"DOT":8};

  DeprecatedGlobbingBehavior = false;

  SpecialOptionsKey = "_options";

  UriEncoderSegmentRegex = /[^a-zA-Z0-9\-\._~!\$&'\(\)\*\+,;=:@]/g;

  ReservedOptions = ['anchor', 'trailing_slash', 'subdomain', 'host', 'port', 'protocol'];

  Utils = {
    configuration: {
      prefix: "",
      default_url_options: {},
      special_options_key: "_options",
      serializer: null
    },
    default_serializer: function(object, prefix) {
      var element, i, j, key, len, prop, s;
      if (prefix == null) {
        prefix = null;
      }
      if (object == null) {
        return "";
      }
      if (!prefix && !(this.get_object_type(object) === "object")) {
        throw new Error("Url parameters should be a javascript hash");
      }
      s = [];
      switch (this.get_object_type(object)) {
        case "array":
          for (i = j = 0, len = object.length; j < len; i = ++j) {
            element = object[i];
            s.push(this.default_serializer(element, prefix + "[]"));
          }
          break;
        case "object":
          for (key in object) {
            if (!hasProp.call(object, key)) continue;
            prop = object[key];
            if ((prop == null) && (prefix != null)) {
              prop = "";
            }
            if (prop != null) {
              if (prefix != null) {
                key = prefix + "[" + key + "]";
              }
              s.push(this.default_serializer(prop, key));
            }
          }
          break;
        default:
          if (object != null) {
            s.push((encodeURIComponent(prefix.toString())) + "=" + (encodeURIComponent(object.toString())));
          }
      }
      if (!s.length) {
        return "";
      }
      return s.join("&");
    },
    serialize: function(object) {
      var custom_serializer;
      custom_serializer = this.configuration.serializer;
      if ((custom_serializer != null) && this.get_object_type(custom_serializer) === "function") {
        return custom_serializer(object);
      } else {
        return this.default_serializer(object);
      }
    },
    clean_path: function(path) {
      var last_index;
      path = path.split("://");
      last_index = path.length - 1;
      path[last_index] = path[last_index].replace(/\/+/g, "/");
      return path.join("://");
    },
    extract_options: function(number_of_params, args) {
      var last_el, options;
      last_el = args[args.length - 1];
      if ((args.length > number_of_params && last_el === void 0) || ((last_el != null) && "object" === this.get_object_type(last_el) && !this.looks_like_serialized_model(last_el))) {
        options = args.pop() || {};
        delete options[this.configuration.special_options_key];
        return options;
      } else {
        return {};
      }
    },
    looks_like_serialized_model: function(object) {
      return !object[this.configuration.special_options_key] && ("id" in object || "to_param" in object);
    },
    path_identifier: function(object) {
      var property;
      if (object === 0) {
        return "0";
      }
      if (!object) {
        return "";
      }
      property = object;
      if (this.get_object_type(object) === "object") {
        if ("to_param" in object) {
          if (object.to_param == null) {
            throw new ParameterMissing("Route parameter missing: to_param");
          }
          property = object.to_param;
        } else if ("id" in object) {
          if (object.id == null) {
            throw new ParameterMissing("Route parameter missing: id");
          }
          property = object.id;
        } else {
          property = object;
        }
        if (this.get_object_type(property) === "function") {
          property = property.call(object);
        }
      }
      return property.toString();
    },
    clone: function(obj) {
      var attr, copy, key;
      if ((obj == null) || "object" !== this.get_object_type(obj)) {
        return obj;
      }
      copy = obj.constructor();
      for (key in obj) {
        if (!hasProp.call(obj, key)) continue;
        attr = obj[key];
        copy[key] = attr;
      }
      return copy;
    },
    merge: function() {
      var tap, xs;
      xs = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      tap = function(o, fn) {
        fn(o);
        return o;
      };
      if ((xs != null ? xs.length : void 0) > 0) {
        return tap({}, function(m) {
          var j, k, len, results, v, x;
          results = [];
          for (j = 0, len = xs.length; j < len; j++) {
            x = xs[j];
            results.push((function() {
              var results1;
              results1 = [];
              for (k in x) {
                v = x[k];
                results1.push(m[k] = v);
              }
              return results1;
            })());
          }
          return results;
        });
      }
    },
    normalize_options: function(parts, required_parts, default_options, actual_parameters) {
      var i, j, key, len, options, part, parts_options, result, route_parts, url_parameters, use_all_parts, value;
      options = this.extract_options(parts.length, actual_parameters);
      if (actual_parameters.length > parts.length) {
        throw new Error("Too many parameters provided for path");
      }
      use_all_parts = actual_parameters.length > required_parts.length;
      parts_options = {};
      for (key in options) {
        if (!hasProp.call(options, key)) continue;
        use_all_parts = true;
        if (this.indexOf(parts, key) >= 0) {
          parts_options[key] = value;
        }
      }
      options = this.merge(this.configuration.default_url_options, default_options, options);
      result = {};
      url_parameters = {};
      result['url_parameters'] = url_parameters;
      for (key in options) {
        if (!hasProp.call(options, key)) continue;
        value = options[key];
        if (this.indexOf(ReservedOptions, key) >= 0) {
          result[key] = value;
        } else {
          url_parameters[key] = value;
        }
      }
      route_parts = use_all_parts ? parts : required_parts;
      i = 0;
      for (j = 0, len = route_parts.length; j < len; j++) {
        part = route_parts[j];
        if (i < actual_parameters.length) {
          if (!parts_options.hasOwnProperty(part)) {
            url_parameters[part] = actual_parameters[i];
            ++i;
          }
        }
      }
      return result;
    },
    build_route: function(parts, required_parts, default_options, route, full_url, args) {
      var options, parameters, result, url, url_params;
      args = Array.prototype.slice.call(args);
      options = this.normalize_options(parts, required_parts, default_options, args);
      parameters = options['url_parameters'];
      result = "" + (this.get_prefix()) + (this.visit(route, parameters));
      url = Utils.clean_path(result);
      if (options['trailing_slash'] === true) {
        url = url.replace(/(.*?)[\/]?$/, "$1/");
      }
      if ((url_params = this.serialize(parameters)).length) {
        url += "?" + url_params;
      }
      url += options.anchor ? "#" + options.anchor : "";
      if (full_url) {
        url = this.route_url(options) + url;
      }
      return url;
    },
    visit: function(route, parameters, optional) {
      var left, left_part, right, right_part, type, value;
      if (optional == null) {
        optional = false;
      }
      type = route[0], left = route[1], right = route[2];
      switch (type) {
        case NodeTypes.GROUP:
          return this.visit(left, parameters, true);
        case NodeTypes.STAR:
          return this.visit_globbing(left, parameters, true);
        case NodeTypes.LITERAL:
        case NodeTypes.SLASH:
        case NodeTypes.DOT:
          return left;
        case NodeTypes.CAT:
          left_part = this.visit(left, parameters, optional);
          right_part = this.visit(right, parameters, optional);
          if (optional && ((this.is_optional_node(left[0]) && !left_part) || ((this.is_optional_node(right[0])) && !right_part))) {
            return "";
          }
          return "" + left_part + right_part;
        case NodeTypes.SYMBOL:
          value = parameters[left];
          delete parameters[left];
          if (value != null) {
            return this.encode_segment(this.path_identifier(value));
          }
          if (optional) {
            return "";
          } else {
            throw new ParameterMissing("Route parameter missing: " + left);
          }
          break;
        default:
          throw new Error("Unknown Rails node type");
      }
    },
    encode_segment: function(segment) {
      return segment.replace(UriEncoderSegmentRegex, function(str) {
        return encodeURIComponent(str);
      });
    },
    is_optional_node: function(node) {
      return this.indexOf([NodeTypes.STAR, NodeTypes.SYMBOL, NodeTypes.CAT], node) >= 0;
    },
    build_path_spec: function(route, wildcard) {
      var left, right, type;
      if (wildcard == null) {
        wildcard = false;
      }
      type = route[0], left = route[1], right = route[2];
      switch (type) {
        case NodeTypes.GROUP:
          return "(" + (this.build_path_spec(left)) + ")";
        case NodeTypes.CAT:
          return "" + (this.build_path_spec(left)) + (this.build_path_spec(right));
        case NodeTypes.STAR:
          return this.build_path_spec(left, true);
        case NodeTypes.SYMBOL:
          if (wildcard === true) {
            return "" + (left[0] === '*' ? '' : '*') + left;
          } else {
            return ":" + left;
          }
          break;
        case NodeTypes.SLASH:
        case NodeTypes.DOT:
        case NodeTypes.LITERAL:
          return left;
        default:
          throw new Error("Unknown Rails node type");
      }
    },
    visit_globbing: function(route, parameters, optional) {
      var left, right, type, value;
      type = route[0], left = route[1], right = route[2];
      value = parameters[left];
      delete parameters[left];
      if (value == null) {
        return this.visit(route, parameters, optional);
      }
      value = (function() {
        switch (this.get_object_type(value)) {
          case "array":
            return value.join("/");
          default:
            return value;
        }
      }).call(this);
      if (DeprecatedGlobbingBehavior) {
        return this.path_identifier(value);
      } else {
        return encodeURI(this.path_identifier(value));
      }
    },
    get_prefix: function() {
      var prefix;
      prefix = this.configuration.prefix;
      if (prefix !== "") {
        prefix = (prefix.match("/$") ? prefix : prefix + "/");
      }
      return prefix;
    },
    route: function(parts_table, default_options, route_spec, full_url) {
      var j, len, part, parts, path_fn, ref, required, required_parts;
      required_parts = [];
      parts = [];
      for (j = 0, len = parts_table.length; j < len; j++) {
        ref = parts_table[j], part = ref[0], required = ref[1];
        parts.push(part);
        if (required) {
          required_parts.push(part);
        }
      }
      path_fn = function() {
        return Utils.build_route(parts, required_parts, default_options, route_spec, full_url, arguments);
      };
      path_fn.required_params = required_parts;
      path_fn.toString = function() {
        return Utils.build_path_spec(route_spec);
      };
      return path_fn;
    },
    route_url: function(route_defaults) {
      var hostname, port, protocol, subdomain;
      if (typeof route_defaults === 'string') {
        return route_defaults;
      }
      hostname = route_defaults.host || Utils.current_host();
      if (!hostname) {
        return '';
      }
      subdomain = route_defaults.subdomain ? route_defaults.subdomain + '.' : '';
      protocol = route_defaults.protocol || Utils.current_protocol();
      port = route_defaults.port || (!route_defaults.host ? Utils.current_port() : void 0);
      port = port ? ":" + port : '';
      return protocol + "://" + subdomain + hostname + port;
    },
    has_location: function() {
      return (typeof window !== "undefined" && window !== null ? window.location : void 0) != null;
    },
    current_host: function() {
      if (this.has_location()) {
        return window.location.hostname;
      } else {
        return null;
      }
    },
    current_protocol: function() {
      if (this.has_location() && window.location.protocol !== '') {
        return window.location.protocol.replace(/:$/, '');
      } else {
        return 'http';
      }
    },
    current_port: function() {
      if (this.has_location() && window.location.port !== '') {
        return window.location.port;
      } else {
        return '';
      }
    },
    _classToTypeCache: null,
    _classToType: function() {
      var j, len, name, ref;
      if (this._classToTypeCache != null) {
        return this._classToTypeCache;
      }
      this._classToTypeCache = {};
      ref = "Boolean Number String Function Array Date RegExp Object Error".split(" ");
      for (j = 0, len = ref.length; j < len; j++) {
        name = ref[j];
        this._classToTypeCache["[object " + name + "]"] = name.toLowerCase();
      }
      return this._classToTypeCache;
    },
    get_object_type: function(obj) {
      if (root.jQuery && (root.jQuery.type != null)) {
        return root.jQuery.type(obj);
      }
      if (obj == null) {
        return "" + obj;
      }
      if (typeof obj === "object" || typeof obj === "function") {
        return this._classToType()[Object.prototype.toString.call(obj)] || "object";
      } else {
        return typeof obj;
      }
    },
    indexOf: function(array, element) {
      if (Array.prototype.indexOf) {
        return array.indexOf(element);
      } else {
        return this.indexOfImplementation(array, element);
      }
    },
    indexOfImplementation: function(array, element) {
      var el, i, j, len, result;
      result = -1;
      for (i = j = 0, len = array.length; j < len; i = ++j) {
        el = array[i];
        if (el === element) {
          result = i;
        }
      }
      return result;
    },
    namespace: function(root, namespace, routes) {
      var index, j, len, part, parts;
      parts = namespace ? namespace.split(".") : [];
      if (parts.length === 0) {
        return routes;
      }
      for (index = j = 0, len = parts.length; j < len; index = ++j) {
        part = parts[index];
        if (index < parts.length - 1) {
          root = (root[part] || (root[part] = {}));
        } else {
          return root[part] = routes;
        }
      }
    },
    configure: function(new_config) {
      return this.configuration = this.merge(this.configuration, new_config);
    },
    config: function() {
      return this.clone(this.configuration);
    },
    make: function() {
      var routes;
      routes = {
// account => /accounts/:id(.:format)
  // function(id, options)
  account: Utils.route([["id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"accounts",false],[2,[7,"/",false],[2,[3,"id",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]),
// account_dashboard => /accounts/:account_id/dashboard(.:format)
  // function(account_id, options)
  account_dashboard: Utils.route([["account_id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"accounts",false],[2,[7,"/",false],[2,[3,"account_id",false],[2,[7,"/",false],[2,[6,"dashboard",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]),
// account_membership => /accounts/:account_id/memberships/:id(.:format)
  // function(account_id, id, options)
  account_membership: Utils.route([["account_id",true],["id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"accounts",false],[2,[7,"/",false],[2,[3,"account_id",false],[2,[7,"/",false],[2,[6,"memberships",false],[2,[7,"/",false],[2,[3,"id",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]),
// account_memberships => /accounts/:account_id/memberships(.:format)
  // function(account_id, options)
  account_memberships: Utils.route([["account_id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"accounts",false],[2,[7,"/",false],[2,[3,"account_id",false],[2,[7,"/",false],[2,[6,"memberships",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]),
// accounts => /accounts(.:format)
  // function(options)
  accounts: Utils.route([["format",false]], {}, [2,[7,"/",false],[2,[6,"accounts",false],[1,[2,[8,".",false],[3,"format",false]],false]]]),
// bucket => /buckets/:id(.:format)
  // function(id, options)
  bucket: Utils.route([["id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"buckets",false],[2,[7,"/",false],[2,[3,"id",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]),
// bucket_message => /buckets/:bucket_id/messages/:id(.:format)
  // function(bucket_id, id, options)
  bucket_message: Utils.route([["bucket_id",true],["id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"buckets",false],[2,[7,"/",false],[2,[3,"bucket_id",false],[2,[7,"/",false],[2,[6,"messages",false],[2,[7,"/",false],[2,[3,"id",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]),
// bucket_message_board => /buckets/:bucket_id/message_board(.:format)
  // function(bucket_id, options)
  bucket_message_board: Utils.route([["bucket_id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"buckets",false],[2,[7,"/",false],[2,[3,"bucket_id",false],[2,[7,"/",false],[2,[6,"message_board",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]),
// bucket_message_board_message_comment => /buckets/:bucket_id/message_board/messages/:message_id/comments/:id(.:format)
  // function(bucket_id, message_id, id, options)
  bucket_message_board_message_comment: Utils.route([["bucket_id",true],["message_id",true],["id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"buckets",false],[2,[7,"/",false],[2,[3,"bucket_id",false],[2,[7,"/",false],[2,[6,"message_board",false],[2,[7,"/",false],[2,[6,"messages",false],[2,[7,"/",false],[2,[3,"message_id",false],[2,[7,"/",false],[2,[6,"comments",false],[2,[7,"/",false],[2,[3,"id",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]]]]]]]),
// bucket_message_board_message_comments => /buckets/:bucket_id/message_board/messages/:message_id/comments(.:format)
  // function(bucket_id, message_id, options)
  bucket_message_board_message_comments: Utils.route([["bucket_id",true],["message_id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"buckets",false],[2,[7,"/",false],[2,[3,"bucket_id",false],[2,[7,"/",false],[2,[6,"message_board",false],[2,[7,"/",false],[2,[6,"messages",false],[2,[7,"/",false],[2,[3,"message_id",false],[2,[7,"/",false],[2,[6,"comments",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]]]]]),
// bucket_message_board_messages => /buckets/:bucket_id/message_board/messages(.:format)
  // function(bucket_id, options)
  bucket_message_board_messages: Utils.route([["bucket_id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"buckets",false],[2,[7,"/",false],[2,[3,"bucket_id",false],[2,[7,"/",false],[2,[6,"message_board",false],[2,[7,"/",false],[2,[6,"messages",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]),
// bucket_recording => /buckets/:bucket_id/recordings/:id(.:format)
  // function(bucket_id, id, options)
  bucket_recording: Utils.route([["bucket_id",true],["id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"buckets",false],[2,[7,"/",false],[2,[3,"bucket_id",false],[2,[7,"/",false],[2,[6,"recordings",false],[2,[7,"/",false],[2,[3,"id",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]),
// bucket_recording_archivals => /buckets/:bucket_id/recordings/:recording_id/archivals(.:format)
  // function(bucket_id, recording_id, options)
  bucket_recording_archivals: Utils.route([["bucket_id",true],["recording_id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"buckets",false],[2,[7,"/",false],[2,[3,"bucket_id",false],[2,[7,"/",false],[2,[6,"recordings",false],[2,[7,"/",false],[2,[3,"recording_id",false],[2,[7,"/",false],[2,[6,"archivals",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]]]),
// bucket_recording_comments => /buckets/:bucket_id/recordings/:recording_id/comments(.:format)
  // function(bucket_id, recording_id, options)
  bucket_recording_comments: Utils.route([["bucket_id",true],["recording_id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"buckets",false],[2,[7,"/",false],[2,[3,"bucket_id",false],[2,[7,"/",false],[2,[6,"recordings",false],[2,[7,"/",false],[2,[3,"recording_id",false],[2,[7,"/",false],[2,[6,"comments",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]]]),
// bucket_recording_copies => /buckets/:bucket_id/recordings/:recording_id/copies(.:format)
  // function(bucket_id, recording_id, options)
  bucket_recording_copies: Utils.route([["bucket_id",true],["recording_id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"buckets",false],[2,[7,"/",false],[2,[3,"bucket_id",false],[2,[7,"/",false],[2,[6,"recordings",false],[2,[7,"/",false],[2,[3,"recording_id",false],[2,[7,"/",false],[2,[6,"copies",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]]]),
// bucket_recording_moves => /buckets/:bucket_id/recordings/:recording_id/moves(.:format)
  // function(bucket_id, recording_id, options)
  bucket_recording_moves: Utils.route([["bucket_id",true],["recording_id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"buckets",false],[2,[7,"/",false],[2,[3,"bucket_id",false],[2,[7,"/",false],[2,[6,"recordings",false],[2,[7,"/",false],[2,[3,"recording_id",false],[2,[7,"/",false],[2,[6,"moves",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]]]),
// bucket_recording_trashings => /buckets/:bucket_id/recordings/:recording_id/trashings(.:format)
  // function(bucket_id, recording_id, options)
  bucket_recording_trashings: Utils.route([["bucket_id",true],["recording_id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"buckets",false],[2,[7,"/",false],[2,[3,"bucket_id",false],[2,[7,"/",false],[2,[6,"recordings",false],[2,[7,"/",false],[2,[3,"recording_id",false],[2,[7,"/",false],[2,[6,"trashings",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]]]),
// bucket_recordings => /buckets/:bucket_id/recordings(.:format)
  // function(bucket_id, options)
  bucket_recordings: Utils.route([["bucket_id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"buckets",false],[2,[7,"/",false],[2,[3,"bucket_id",false],[2,[7,"/",false],[2,[6,"recordings",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]),
// bucket_todo => /buckets/:bucket_id/todos/:id(.:format)
  // function(bucket_id, id, options)
  bucket_todo: Utils.route([["bucket_id",true],["id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"buckets",false],[2,[7,"/",false],[2,[3,"bucket_id",false],[2,[7,"/",false],[2,[6,"todos",false],[2,[7,"/",false],[2,[3,"id",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]),
// bucket_todo_completion => /buckets/:bucket_id/todos/:todo_id/completion(.:format)
  // function(bucket_id, todo_id, options)
  bucket_todo_completion: Utils.route([["bucket_id",true],["todo_id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"buckets",false],[2,[7,"/",false],[2,[3,"bucket_id",false],[2,[7,"/",false],[2,[6,"todos",false],[2,[7,"/",false],[2,[3,"todo_id",false],[2,[7,"/",false],[2,[6,"completion",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]]]),
// bucket_todo_list => /buckets/:bucket_id/todo_lists/:id(.:format)
  // function(bucket_id, id, options)
  bucket_todo_list: Utils.route([["bucket_id",true],["id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"buckets",false],[2,[7,"/",false],[2,[3,"bucket_id",false],[2,[7,"/",false],[2,[6,"todo_lists",false],[2,[7,"/",false],[2,[3,"id",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]),
// bucket_todo_lists => /buckets/:bucket_id/todo_lists(.:format)
  // function(bucket_id, options)
  bucket_todo_lists: Utils.route([["bucket_id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"buckets",false],[2,[7,"/",false],[2,[3,"bucket_id",false],[2,[7,"/",false],[2,[6,"todo_lists",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]),
// bucket_todo_set => /buckets/:bucket_id/todo_sets/:id(.:format)
  // function(bucket_id, id, options)
  bucket_todo_set: Utils.route([["bucket_id",true],["id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"buckets",false],[2,[7,"/",false],[2,[3,"bucket_id",false],[2,[7,"/",false],[2,[6,"todo_sets",false],[2,[7,"/",false],[2,[3,"id",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]),
// bucket_todos => /buckets/:bucket_id/todos(.:format)
  // function(bucket_id, options)
  bucket_todos: Utils.route([["bucket_id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"buckets",false],[2,[7,"/",false],[2,[3,"bucket_id",false],[2,[7,"/",false],[2,[6,"todos",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]),
// buckets => /buckets(.:format)
  // function(options)
  buckets: Utils.route([["format",false]], {}, [2,[7,"/",false],[2,[6,"buckets",false],[1,[2,[8,".",false],[3,"format",false]],false]]]),
// cancel_user_registration => /users/cancel(.:format)
  // function(options)
  cancel_user_registration: Utils.route([["format",false]], {}, [2,[7,"/",false],[2,[6,"users",false],[2,[7,"/",false],[2,[6,"cancel",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]),
// choose_launch_pad => /launch_pad/choose(.:format)
  // function(options)
  choose_launch_pad: Utils.route([["format",false]], {}, [2,[7,"/",false],[2,[6,"launch_pad",false],[2,[7,"/",false],[2,[6,"choose",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]),
// destroy_user_session => /users/sign_out(.:format)
  // function(options)
  destroy_user_session: Utils.route([["format",false]], {}, [2,[7,"/",false],[2,[6,"users",false],[2,[7,"/",false],[2,[6,"sign_out",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]),
// edit_account => /accounts/:id/edit(.:format)
  // function(id, options)
  edit_account: Utils.route([["id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"accounts",false],[2,[7,"/",false],[2,[3,"id",false],[2,[7,"/",false],[2,[6,"edit",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]),
// edit_account_dashboard => /accounts/:account_id/dashboard/edit(.:format)
  // function(account_id, options)
  edit_account_dashboard: Utils.route([["account_id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"accounts",false],[2,[7,"/",false],[2,[3,"account_id",false],[2,[7,"/",false],[2,[6,"dashboard",false],[2,[7,"/",false],[2,[6,"edit",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]),
// edit_account_membership => /accounts/:account_id/memberships/:id/edit(.:format)
  // function(account_id, id, options)
  edit_account_membership: Utils.route([["account_id",true],["id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"accounts",false],[2,[7,"/",false],[2,[3,"account_id",false],[2,[7,"/",false],[2,[6,"memberships",false],[2,[7,"/",false],[2,[3,"id",false],[2,[7,"/",false],[2,[6,"edit",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]]]),
// edit_bucket => /buckets/:id/edit(.:format)
  // function(id, options)
  edit_bucket: Utils.route([["id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"buckets",false],[2,[7,"/",false],[2,[3,"id",false],[2,[7,"/",false],[2,[6,"edit",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]),
// edit_bucket_message => /buckets/:bucket_id/messages/:id/edit(.:format)
  // function(bucket_id, id, options)
  edit_bucket_message: Utils.route([["bucket_id",true],["id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"buckets",false],[2,[7,"/",false],[2,[3,"bucket_id",false],[2,[7,"/",false],[2,[6,"messages",false],[2,[7,"/",false],[2,[3,"id",false],[2,[7,"/",false],[2,[6,"edit",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]]]),
// edit_bucket_message_board => /buckets/:bucket_id/message_board/edit(.:format)
  // function(bucket_id, options)
  edit_bucket_message_board: Utils.route([["bucket_id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"buckets",false],[2,[7,"/",false],[2,[3,"bucket_id",false],[2,[7,"/",false],[2,[6,"message_board",false],[2,[7,"/",false],[2,[6,"edit",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]),
// edit_bucket_message_board_message_comment => /buckets/:bucket_id/message_board/messages/:message_id/comments/:id/edit(.:format)
  // function(bucket_id, message_id, id, options)
  edit_bucket_message_board_message_comment: Utils.route([["bucket_id",true],["message_id",true],["id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"buckets",false],[2,[7,"/",false],[2,[3,"bucket_id",false],[2,[7,"/",false],[2,[6,"message_board",false],[2,[7,"/",false],[2,[6,"messages",false],[2,[7,"/",false],[2,[3,"message_id",false],[2,[7,"/",false],[2,[6,"comments",false],[2,[7,"/",false],[2,[3,"id",false],[2,[7,"/",false],[2,[6,"edit",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]]]]]]]]]),
// edit_bucket_recording => /buckets/:bucket_id/recordings/:id/edit(.:format)
  // function(bucket_id, id, options)
  edit_bucket_recording: Utils.route([["bucket_id",true],["id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"buckets",false],[2,[7,"/",false],[2,[3,"bucket_id",false],[2,[7,"/",false],[2,[6,"recordings",false],[2,[7,"/",false],[2,[3,"id",false],[2,[7,"/",false],[2,[6,"edit",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]]]),
// edit_bucket_todo => /buckets/:bucket_id/todos/:id/edit(.:format)
  // function(bucket_id, id, options)
  edit_bucket_todo: Utils.route([["bucket_id",true],["id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"buckets",false],[2,[7,"/",false],[2,[3,"bucket_id",false],[2,[7,"/",false],[2,[6,"todos",false],[2,[7,"/",false],[2,[3,"id",false],[2,[7,"/",false],[2,[6,"edit",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]]]),
// edit_bucket_todo_list => /buckets/:bucket_id/todo_lists/:id/edit(.:format)
  // function(bucket_id, id, options)
  edit_bucket_todo_list: Utils.route([["bucket_id",true],["id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"buckets",false],[2,[7,"/",false],[2,[3,"bucket_id",false],[2,[7,"/",false],[2,[6,"todo_lists",false],[2,[7,"/",false],[2,[3,"id",false],[2,[7,"/",false],[2,[6,"edit",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]]]),
// edit_project => /projects/:id/edit(.:format)
  // function(id, options)
  edit_project: Utils.route([["id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"projects",false],[2,[7,"/",false],[2,[3,"id",false],[2,[7,"/",false],[2,[6,"edit",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]),
// edit_project_membership => /projects/:project_id/memberships/:id/edit(.:format)
  // function(project_id, id, options)
  edit_project_membership: Utils.route([["project_id",true],["id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"projects",false],[2,[7,"/",false],[2,[3,"project_id",false],[2,[7,"/",false],[2,[6,"memberships",false],[2,[7,"/",false],[2,[3,"id",false],[2,[7,"/",false],[2,[6,"edit",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]]]),
// edit_project_todo_list => /projects/:project_id/todo_lists/:id/edit(.:format)
  // function(project_id, id, options)
  edit_project_todo_list: Utils.route([["project_id",true],["id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"projects",false],[2,[7,"/",false],[2,[3,"project_id",false],[2,[7,"/",false],[2,[6,"todo_lists",false],[2,[7,"/",false],[2,[3,"id",false],[2,[7,"/",false],[2,[6,"edit",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]]]),
// edit_user_password => /users/password/edit(.:format)
  // function(options)
  edit_user_password: Utils.route([["format",false]], {}, [2,[7,"/",false],[2,[6,"users",false],[2,[7,"/",false],[2,[6,"password",false],[2,[7,"/",false],[2,[6,"edit",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]),
// edit_user_registration => /users/edit(.:format)
  // function(options)
  edit_user_registration: Utils.route([["format",false]], {}, [2,[7,"/",false],[2,[6,"users",false],[2,[7,"/",false],[2,[6,"edit",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]),
// launch_pad => /launch_pad(.:format)
  // function(options)
  launch_pad: Utils.route([["format",false]], {}, [2,[7,"/",false],[2,[6,"launch_pad",false],[1,[2,[8,".",false],[3,"format",false]],false]]]),
// new_account => /accounts/new(.:format)
  // function(options)
  new_account: Utils.route([["format",false]], {}, [2,[7,"/",false],[2,[6,"accounts",false],[2,[7,"/",false],[2,[6,"new",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]),
// new_account_dashboard => /accounts/:account_id/dashboard/new(.:format)
  // function(account_id, options)
  new_account_dashboard: Utils.route([["account_id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"accounts",false],[2,[7,"/",false],[2,[3,"account_id",false],[2,[7,"/",false],[2,[6,"dashboard",false],[2,[7,"/",false],[2,[6,"new",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]),
// new_account_membership => /accounts/:account_id/memberships/new(.:format)
  // function(account_id, options)
  new_account_membership: Utils.route([["account_id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"accounts",false],[2,[7,"/",false],[2,[3,"account_id",false],[2,[7,"/",false],[2,[6,"memberships",false],[2,[7,"/",false],[2,[6,"new",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]),
// new_bucket => /buckets/new(.:format)
  // function(options)
  new_bucket: Utils.route([["format",false]], {}, [2,[7,"/",false],[2,[6,"buckets",false],[2,[7,"/",false],[2,[6,"new",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]),
// new_bucket_message_board => /buckets/:bucket_id/message_board/new(.:format)
  // function(bucket_id, options)
  new_bucket_message_board: Utils.route([["bucket_id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"buckets",false],[2,[7,"/",false],[2,[3,"bucket_id",false],[2,[7,"/",false],[2,[6,"message_board",false],[2,[7,"/",false],[2,[6,"new",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]),
// new_bucket_message_board_message => /buckets/:bucket_id/message_board/messages/new(.:format)
  // function(bucket_id, options)
  new_bucket_message_board_message: Utils.route([["bucket_id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"buckets",false],[2,[7,"/",false],[2,[3,"bucket_id",false],[2,[7,"/",false],[2,[6,"message_board",false],[2,[7,"/",false],[2,[6,"messages",false],[2,[7,"/",false],[2,[6,"new",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]]]),
// new_bucket_message_board_message_comment => /buckets/:bucket_id/message_board/messages/:message_id/comments/new(.:format)
  // function(bucket_id, message_id, options)
  new_bucket_message_board_message_comment: Utils.route([["bucket_id",true],["message_id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"buckets",false],[2,[7,"/",false],[2,[3,"bucket_id",false],[2,[7,"/",false],[2,[6,"message_board",false],[2,[7,"/",false],[2,[6,"messages",false],[2,[7,"/",false],[2,[3,"message_id",false],[2,[7,"/",false],[2,[6,"comments",false],[2,[7,"/",false],[2,[6,"new",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]]]]]]]),
// new_bucket_recording => /buckets/:bucket_id/recordings/new(.:format)
  // function(bucket_id, options)
  new_bucket_recording: Utils.route([["bucket_id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"buckets",false],[2,[7,"/",false],[2,[3,"bucket_id",false],[2,[7,"/",false],[2,[6,"recordings",false],[2,[7,"/",false],[2,[6,"new",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]),
// new_bucket_recording_comment => /buckets/:bucket_id/recordings/:recording_id/comments/new(.:format)
  // function(bucket_id, recording_id, options)
  new_bucket_recording_comment: Utils.route([["bucket_id",true],["recording_id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"buckets",false],[2,[7,"/",false],[2,[3,"bucket_id",false],[2,[7,"/",false],[2,[6,"recordings",false],[2,[7,"/",false],[2,[3,"recording_id",false],[2,[7,"/",false],[2,[6,"comments",false],[2,[7,"/",false],[2,[6,"new",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]]]]]),
// new_bucket_recording_copy => /buckets/:bucket_id/recordings/:recording_id/copies/new(.:format)
  // function(bucket_id, recording_id, options)
  new_bucket_recording_copy: Utils.route([["bucket_id",true],["recording_id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"buckets",false],[2,[7,"/",false],[2,[3,"bucket_id",false],[2,[7,"/",false],[2,[6,"recordings",false],[2,[7,"/",false],[2,[3,"recording_id",false],[2,[7,"/",false],[2,[6,"copies",false],[2,[7,"/",false],[2,[6,"new",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]]]]]),
// new_bucket_recording_move => /buckets/:bucket_id/recordings/:recording_id/moves/new(.:format)
  // function(bucket_id, recording_id, options)
  new_bucket_recording_move: Utils.route([["bucket_id",true],["recording_id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"buckets",false],[2,[7,"/",false],[2,[3,"bucket_id",false],[2,[7,"/",false],[2,[6,"recordings",false],[2,[7,"/",false],[2,[3,"recording_id",false],[2,[7,"/",false],[2,[6,"moves",false],[2,[7,"/",false],[2,[6,"new",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]]]]]),
// new_bucket_todo => /buckets/:bucket_id/todos/new(.:format)
  // function(bucket_id, options)
  new_bucket_todo: Utils.route([["bucket_id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"buckets",false],[2,[7,"/",false],[2,[3,"bucket_id",false],[2,[7,"/",false],[2,[6,"todos",false],[2,[7,"/",false],[2,[6,"new",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]),
// new_bucket_todo_list => /buckets/:bucket_id/todo_lists/new(.:format)
  // function(bucket_id, options)
  new_bucket_todo_list: Utils.route([["bucket_id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"buckets",false],[2,[7,"/",false],[2,[3,"bucket_id",false],[2,[7,"/",false],[2,[6,"todo_lists",false],[2,[7,"/",false],[2,[6,"new",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]),
// new_project => /projects/new(.:format)
  // function(options)
  new_project: Utils.route([["format",false]], {}, [2,[7,"/",false],[2,[6,"projects",false],[2,[7,"/",false],[2,[6,"new",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]),
// new_project_membership => /projects/:project_id/memberships/new(.:format)
  // function(project_id, options)
  new_project_membership: Utils.route([["project_id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"projects",false],[2,[7,"/",false],[2,[3,"project_id",false],[2,[7,"/",false],[2,[6,"memberships",false],[2,[7,"/",false],[2,[6,"new",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]),
// new_project_todo_list => /projects/:project_id/todo_lists/new(.:format)
  // function(project_id, options)
  new_project_todo_list: Utils.route([["project_id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"projects",false],[2,[7,"/",false],[2,[3,"project_id",false],[2,[7,"/",false],[2,[6,"todo_lists",false],[2,[7,"/",false],[2,[6,"new",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]),
// new_user_confirmation => /users/confirmation/new(.:format)
  // function(options)
  new_user_confirmation: Utils.route([["format",false]], {}, [2,[7,"/",false],[2,[6,"users",false],[2,[7,"/",false],[2,[6,"confirmation",false],[2,[7,"/",false],[2,[6,"new",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]),
// new_user_password => /users/password/new(.:format)
  // function(options)
  new_user_password: Utils.route([["format",false]], {}, [2,[7,"/",false],[2,[6,"users",false],[2,[7,"/",false],[2,[6,"password",false],[2,[7,"/",false],[2,[6,"new",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]),
// new_user_registration => /users/sign_up(.:format)
  // function(options)
  new_user_registration: Utils.route([["format",false]], {}, [2,[7,"/",false],[2,[6,"users",false],[2,[7,"/",false],[2,[6,"sign_up",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]),
// new_user_session => /users/sign_in(.:format)
  // function(options)
  new_user_session: Utils.route([["format",false]], {}, [2,[7,"/",false],[2,[6,"users",false],[2,[7,"/",false],[2,[6,"sign_in",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]),
// new_user_unlock => /users/unlock/new(.:format)
  // function(options)
  new_user_unlock: Utils.route([["format",false]], {}, [2,[7,"/",false],[2,[6,"users",false],[2,[7,"/",false],[2,[6,"unlock",false],[2,[7,"/",false],[2,[6,"new",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]),
// project => /projects/:id(.:format)
  // function(id, options)
  project: Utils.route([["id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"projects",false],[2,[7,"/",false],[2,[3,"id",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]),
// project_membership => /projects/:project_id/memberships/:id(.:format)
  // function(project_id, id, options)
  project_membership: Utils.route([["project_id",true],["id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"projects",false],[2,[7,"/",false],[2,[3,"project_id",false],[2,[7,"/",false],[2,[6,"memberships",false],[2,[7,"/",false],[2,[3,"id",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]),
// project_memberships => /projects/:project_id/memberships(.:format)
  // function(project_id, options)
  project_memberships: Utils.route([["project_id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"projects",false],[2,[7,"/",false],[2,[3,"project_id",false],[2,[7,"/",false],[2,[6,"memberships",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]),
// project_todo_list => /projects/:project_id/todo_lists/:id(.:format)
  // function(project_id, id, options)
  project_todo_list: Utils.route([["project_id",true],["id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"projects",false],[2,[7,"/",false],[2,[3,"project_id",false],[2,[7,"/",false],[2,[6,"todo_lists",false],[2,[7,"/",false],[2,[3,"id",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]]]),
// project_todo_lists => /projects/:project_id/todo_lists(.:format)
  // function(project_id, options)
  project_todo_lists: Utils.route([["project_id",true],["format",false]], {}, [2,[7,"/",false],[2,[6,"projects",false],[2,[7,"/",false],[2,[3,"project_id",false],[2,[7,"/",false],[2,[6,"todo_lists",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]]),
// projects => /projects(.:format)
  // function(options)
  projects: Utils.route([["format",false]], {}, [2,[7,"/",false],[2,[6,"projects",false],[1,[2,[8,".",false],[3,"format",false]],false]]]),
// root => /
  // function(options)
  root: Utils.route([], {}, [7,"/",false]),
// unauthenticated_root => /
  // function(options)
  unauthenticated_root: Utils.route([], {}, [7,"/",false]),
// user_confirmation => /users/confirmation(.:format)
  // function(options)
  user_confirmation: Utils.route([["format",false]], {}, [2,[7,"/",false],[2,[6,"users",false],[2,[7,"/",false],[2,[6,"confirmation",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]),
// user_password => /users/password(.:format)
  // function(options)
  user_password: Utils.route([["format",false]], {}, [2,[7,"/",false],[2,[6,"users",false],[2,[7,"/",false],[2,[6,"password",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]),
// user_registration => /users(.:format)
  // function(options)
  user_registration: Utils.route([["format",false]], {}, [2,[7,"/",false],[2,[6,"users",false],[1,[2,[8,".",false],[3,"format",false]],false]]]),
// user_session => /users/sign_in(.:format)
  // function(options)
  user_session: Utils.route([["format",false]], {}, [2,[7,"/",false],[2,[6,"users",false],[2,[7,"/",false],[2,[6,"sign_in",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]),
// user_unlock => /users/unlock(.:format)
  // function(options)
  user_unlock: Utils.route([["format",false]], {}, [2,[7,"/",false],[2,[6,"users",false],[2,[7,"/",false],[2,[6,"unlock",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]),
// users => /users(.:format)
  // function(options)
  users: Utils.route([["format",false]], {}, [2,[7,"/",false],[2,[6,"users",false],[1,[2,[8,".",false],[3,"format",false]],false]]]),
// users_password => /users/password(.:format)
  // function(options)
  users_password: Utils.route([["format",false]], {}, [2,[7,"/",false],[2,[6,"users",false],[2,[7,"/",false],[2,[6,"password",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]])}
;
      routes.configure = function(config) {
        return Utils.configure(config);
      };
      routes.config = function() {
        return Utils.config();
      };
      Object.defineProperty(routes, 'defaults', {
        get: function() {
          throw new Error("Routes" + ".defaults is removed. Use " + "Routes" + ".configure() instead.");
        },
        set: function(value) {}
      });
      routes.default_serializer = function(object, prefix) {
        return Utils.default_serializer(object, prefix);
      };
      return Utils.namespace(root, "Routes", routes);
    }
  };

  result = Utils.make();

  if (typeof define === "function" && define.amd) {
    define([], function() {
      return result;
    });
  }

  return result;

}).call(this);
