---

shared_default: &shared_default
  adapter: postgresql
  encoding: unicode

development:
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test:
  url: <%= ENV["DATABASE_URL"].gsub("development", "test") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
